// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Echo",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "Echo",
            targets: ["AppModule"],
            bundleIdentifier: "com.jayc.echo",
            teamIdentifier: "3JB47XFYY5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeLeft,
                .landscapeRight,
                .portraitUpsideDown
            ],
            capabilities: [
                .microphone(purposeString: "Echo needs access to your microphone to record audio."),
                .speechRecognition(purposeString: "Echo analyzes your voice to provide accurate results."),
                .camera(purposeString: "Echo uses the camera to help you analyze your non-verbal communication like posture and gaze.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
